AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - "db/**/*"

# To make Lorenzo happy
Layout/AlignHash:
  EnforcedColonStyle: table

# Increase line length to 120
Metrics/LineLength:
  Max: 120

# Exclude class and method length for test
Metrics/BlockLength:
  Exclude:
    - "test/**/*"
Metrics/ClassLength:
  Exclude:
    - "test/**/*"
Metrics/MethodLength:
  Exclude:
    - "test/**/*"
    
# Disable Style/Documentation because...
Style/Documentation:
  Enabled: false

# Use double quotes ALL THE TIME!!!
Style/StringLiterals:
  EnforcedStyle: double_quotes
