AllCops:
  TargetRubyVersion: 2.7.0
Layout/LineLength:
  Max: 120 # Increase line length to 120
  Exclude:
    - "config/routes.rb"
Metrics/BlockLength: # Exclude block length for routes and tests
  Exclude:
    - "config/routes.rb"
    - "test/**/*"
Metrics/ClassLength: # Exclude class length for tests
  Exclude:
    - "test/**/*"
Metrics/MethodLength: # Exclude method length for tests
  Exclude:
    - "test/**/*"
Style/DoubleNegation:
  Enabled: false
Style/Documentation:
  Enabled: false # Disable Style/Documentation because...
Style/HashEachMethods:
  Enabled: true # These will be enabled by default at some point, but adding for now to stop Rubocop complaining...
Style/HashTransformKeys:
  Enabled: true # These will be enabled by default at some point, but adding for now to stop Rubocop complaining...
Style/HashTransformValues:
  Enabled: true # These will be enabled by default at some point, but adding for now to stop Rubocop complaining...
Style/StringLiterals:
  EnforcedStyle: double_quotes # Use double quotes ALL THE TIME!!!
