AllCops:
  TargetRubyVersion: 2.7.1
  Exclude:
    - "**/*/schema.rb"
    - "Gemfile.lock"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
Layout/LineLength:
  Max: 120 # Increase line length to 120
  Exclude:
    - "config/routes.rb"
Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - "Gemfile"
    - "config/routes.rb"
    - "test/**/*"
Metrics/ClassLength:
  Exclude:
    - "test/**/*"
Metrics/MethodLength:
  Exclude:
    - "test/**/*"
Style/DoubleNegation:
  Enabled: false
Style/Documentation:
  Enabled: false # Disable Style/Documentation because...
Style/StringLiterals:
  EnforcedStyle: double_quotes # Use double quotes ALL THE TIME!!!
