AllCops:
  TargetRubyVersion: 2.7.0
Layout/LineLength:
  Max: 120 # Increase line length to 120
  Exclude:
    - "config/routes.rb"
Metrics/BlockLength: # Exclude block length for routes and specs
  Exclude:
    - "config/routes.rb"
    - "spec/**/*.rb"
Metrics/ClassLength: # Exclude class length for specs
  Exclude:
    - "spec/**/*.rb"
Metrics/MethodLength: # Exclude method length for specs
  Exclude:
    - "spec/**/*.rb"
Style/DoubleNegation:
  Enabled: false
Style/Documentation:
  Enabled: false # Disable Style/Documentation because...
Style/StringLiterals:
  EnforcedStyle: double_quotes # Use double quotes ALL THE TIME!!!
