AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - "db/*"
    - "db/**/*"
    - "db/fixtures/**/*"
    - "Gemfile*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

# Increase line length to 120
Metrics/LineLength:
  Max: 120
  Exclude:
    - "config/routes.rb"
# Exclude class and method length for test
Metrics/BlockLength:
  Exclude:
    - "config/routes.rb"
    - "test/**/*"
Metrics/ClassLength:
  Exclude:
    - "test/**/*"
Metrics/MethodLength:
  Exclude:
    - "test/**/*"

# Disable Style/Documentation because...
Style/Documentation:
  Enabled: false

# Use double quotes ALL THE TIME!!!
Style/StringLiterals:
  EnforcedStyle: double_quotes
