AllCops:
  Exclude:
    - "**/*/schema.rb"
    - "Gemfile.lock"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
  TargetRubyVersion: 2.7.2
Layout/LineLength:
  Exclude:
    - config/routes.rb
  Max: 120
Metrics/AbcSize:
  Exclude:
    - db/migrate/**/*
Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - Gemfile
    - config/routes.rb
    - db/migrate/**/*
    - spec/**/*
    - test/**/*
Metrics/ClassLength:
  Exclude:
    - db/migrate/**/*
    - spec/**/*
    - test/**/*
Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*
    - spec/**/*
    - test/**/*
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
