AllCops:
  TargetRubyVersion: 2.7.0
Layout/LineLength:
  Max: 120 # Increase line length to 120
  Exclude:
    - "config/routes.rb"
Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - "Gemfile"
    - "config/routes.rb"
    - "test/**/*"
Metrics/ClassLength:
  Exclude:
    - "test/**/*"
Metrics/MethodLength:
  Exclude:
    - "test/**/*"
Style/DoubleNegation:
  Enabled: false
Style/Documentation:
  Enabled: false # Disable Style/Documentation because...
Style/StringLiterals:
  EnforcedStyle: double_quotes # Use double quotes ALL THE TIME!!!
# These cops are currently pending and will be enabled by default at some point, but adding for now to stop Rubocop
# complaining...
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
