version: 2.1

jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/ruby:2.7.1
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run:
          name: Which bundler?
          command: bundle -v
      - restore_cache:
          keys:
            - boxt-ruby-style-guide-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle Install
          command: bundle install
      - save_cache:
          key: boxt-ruby-style-guide-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Run tests
          command: bundle exec rake test | circleci tests split --split-by=timings
      - run:
          name: Run Rubocop
          command: |
            BASE_REVISION=${1:<< pipeline.git.base_revision >>}
            bundle exec rake lint:rubocop RUBOCOP_LINT_BASE=$BASE_REVISION
      - store_test_results:
          path: test_results
